version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "tg-bot"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-oe2n5vcjzx54"
s3_prefix = "tg-bot"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

